### ISSUE TITLE
Nomenclature Screenshots Messed Up

### ISSUE THREAD

**Issue by flueko** [ghalter/VIAN#237]
Screenshots suddenly get a weird nomenclature: 2_1<core.container.screenshot.ScreenshotGroup object at 0x1c66bde0f0>_4400_1_1

**Comment by ghalter** [comment]
This is during export?

**Comment by ghalter** [comment]
Screenshot Groups have been exported by Object name instead of ScreenshotGroup.get_name() 
To omit the name of the screenshot group completely, adapt the screenshot export dialog setting. 

I also removed the behaviour of not have an underline between screenshot group and segment id: 
What was 12_3a_13_1_1 is now 12_3_a_13_1_1 
Or formally: ID_Segment_ID_ScreenshoutGroup.name_MovieID

**Comment by flueko** [comment]
Actually 12_3a_13_1_1 is better, because this is how we call the segements, if we have subsegmentation.

**Comment by ghalter** [comment]
Yes, I know, however, I don't think this feature has ever been used in VIAN, 
for other users, this will definitely be confusing and look like a bug: 
All items are splitted by an underscore, except screenshot groups. Maybe its better to keep this concise, it's also easy to further process it, with an underscore.

**Comment by ghalter** [comment]
We can, on course, use an entirely different nomenclature editor, which allows this feature, bit this would include a bit more of architecture.
